### ISSUE TITLE
ServiceWorker error: node_modules inside staticFileGlobs

### ISSUE THREAD

**Issue by andrealeone** [LionAndTheFellows/TelegramClient#5]
Inside [gulpfile.js](https://github.com/LionAndTheFellows/TelegramClient/blob/master/gulpfile.js), the task `'sw'` is meant to run the *sw-precache* process on all the directories that have been declared with `staticFileGlobs`. With
```
staticFileGlobs: [
  './**',
  './**/*'
],
```
every file and folder in the root is automatically put inside the `precacheConfig` array of the outputted [service-worker.js](https://github.com/LionAndTheFellows/TelegramClient/blob/dev/service-worker.js) file. The *node_modules* folder is inside this array too, and here they come: **more than two thousand  and a half 404 error status** inside the console.

**Comment by jackstonebridge** [comment]
Yeah, right, I didn't notice. New branch @andrealeone?

**Comment by andrealeone** [comment]
@LionAndTheFellows/swdev: [_SW-fix-config](https://github.com/LionAndTheFellows/TelegramClient/tree/_SW-fix-config) is the branch to solve this bug.
For this, 2 reviews needed. [*Fetch*&*Pull* and then *PR*]

**Comment by andrealeone** [comment]
Solved.
