### ISSUE TITLE
CW error

### ISSUE THREAD

**Issue by jackstonebridge** [LionAndTheFellows/TelegramClient#7]
Loading the compressed version of [js/lib/crypto_worker.js](https://github.com/LionAndTheFellows/TelegramClient/blob/master/js/lib/crypto_worker.js), the DevTools console returns an `ErrorEvent` with the message *`"Uncaught SyntaxError: Unexpected token break"`*.
The library core seems not to be loaded: the [polyfill.js](https://github.com/LionAndTheFellows/TelegramClient/blob/master/js/lib/polyfill.js) and the other vendor scripts.

What do you think @LionAndTheFellows/swdev? Can it be something related to the ServiceWorker?

**Comment by andrealeone** [comment]
Apparently it is only a syntax problem.

> What do you think @LionAndTheFellows/swdev?
Can it be something related to the ServiceWorker?

Perhaps. Anyway, we can handle it individually - without interfering with the [_SW-update](https://github.com/LionAndTheFellows/TelegramClient/tree/_SW-update) branch.

**Comment by andrealeone** [comment]
@LionAndTheFellows/swdev: [_CW-fix](https://github.com/LionAndTheFellows/TelegramClient/tree/_CW-fix) is the branch to solve this bug.
For this, 2 reviews needed. [Fetch&Pull and then PR]
